import type { Genero } from "./types"

// 100 vilões únicos, divididos por gênero — cada ingresso sorteia um vilão do
// mesmo gênero detectado no nome da pessoa, sem repetir enquanto houver disponíveis.
export const VILLAINS_MASCULINO: string[] = [
  "O Lobisomem",
  "O Espantalho",
  "O Coveiro",
  "O Fantasma Sombrio",
  "O Palhaço Sinistro",
  "O Corvo Negro",
  "O Necromante",
  "O Verme-Rei",
  "O Príncipe da Noite",
  "O Licantropo Alfa",
  "O Rei dos Espectros",
  "O Carniceiro Sem Cara",
  "O Demônio da Meia-Noite",
  "O Ceifador Pálido",
  "O Homem de Sebo",
  "O Doutor da Peste",
  "O Barqueiro do Aqueronte",
  "O Cavaleiro Sem Cabeça",
  "O Estripador de Whitechapel",
  "O Golem de Barro",
  "O Espectro do Farol",
  "O Carrasco Encapuzado",
  "O Pesadelo de Elm",
  "O Colecionador de Almas",
  "O Homem-Bode",
  "O Enterrador de Vivos",
  "O Ventríloquo Maldito",
  "O Regente das Trevas",
  "O Cão do Inferno",
  "O Profeta Cego",
  "O Relojoeiro da Morte",
  "O Barão do Sangue",
  "O Homem de Neblina",
  "O Espantalho Faminto",
  "O Grão-Inquisidor",
  "O Andarilho da Bruma",
  "O Cirurgião Louco",
  "O Rei Cadáver",
  "O Guardião do Ossário",
  "O Fantasma da Ópera",
  "O Vampiro dos Cárpatos",
  "O Duque das Moscas",
  "O Semeador de Pragas",
  "O Homem do Saco",
  "O Cavaleiro da Peste",
  "O Coveiro Insone",
  "O Príncipe Escarlate",
  "O Palhaço do Esgoto",
  "O Senhor das Sanguessugas",
  "O Espectro do Manicômio",
  "O Último Coveiro",
  "Drácula",
  "Frankenstein",
]

export const VILLAINS_FEMININO: string[] = [
  "A Múmia",
  "A Bruxa Negra",
  "A Noiva Cadáver",
  "A Condessa Batória",
  "A Banshee",
  "A Dama Vermelha",
  "A Sereia Negra",
  "A Feiticeira do Pântano",
  "A Rainha de Gelo",
  "A Viúva Enforcada",
  "A Boneca de Porcelana",
  "A Freira Cega",
  "A Dama de Preto",
  "A Vampira de Praga",
  "A Alma Penada",
  "A Múmia da Cripta",
  "A Bruxa de Endor",
  "A Sirigaita do Cemitério",
  "A Menina do Poço",
  "A Dama Branca",
  "A Sombra Rastejante",
  "A Rainha das Aranhas",
  "A Costureira de Peles",
  "A Serva de Hécate",
  "A Dama dos Corvos",
  "A Bailarina Quebrada",
  "A Súcubo Escarlate",
  "A Órfã Amaldiçoada",
  "A Rainha Carmesim",
  "A Viúva das Sete Faces",
  "A Sereia dos Naufrágios",
  "A Feiticeira Sem Nome",
  "A Dama de Cinzas",
  "A Sacerdotisa Negra",
  "A Bruxa de Salem",
  "A Noiva de Sangue",
  "A Mão Estrangeira",
  "A Dama Sem Rosto",
  "A Rainha dos Mortos",
  "A Feiticeira de Cera",
  "A Aranha-Rainha do Sótão",
  "A Dama do Espelho",
  "A Bruxa das Marés",
  "A Dançarina de Ossos",
  "A Viúva de Véu Negro",
  "A Deusa das Lágrimas",
  "A Dama da Foice",
  "A Costureira de Almas",
  "A Rainha do Nevoeiro",
  "A Bruxa do Espelho Rachado",
  "A Sentinela da Cripta",
  "A Governanta da Casa Vazia",
]

// Retorna um vilão ainda não usado, sorteado do conjunto do gênero informado;
// se todos do gênero já foram usados, permite repetir dentro do mesmo conjunto.
export function pickVillain(genero: Genero, used: string[]): string {
  const lista = genero === "feminino" ? VILLAINS_FEMININO : VILLAINS_MASCULINO
  const disponiveis = lista.filter((v) => !used.includes(v))
  const pool = disponiveis.length > 0 ? disponiveis : lista
  return pool[Math.floor(Math.random() * pool.length)]
}
