// 100 vilões únicos — cada ingresso sorteia um sem repetir enquanto houver disponíveis.
export const VILLAINS: string[] = [
  "Drácula",
  "Frankenstein",
  "A Múmia",
  "O Lobisomem",
  "A Bruxa Negra",
  "O Espantalho",
  "O Coveiro",
  "A Noiva Cadáver",
  "O Fantasma Sombrio",
  "O Palhaço Sinistro",
  "O Corvo Negro",
  "O Necromante",
  "A Condessa Batória",
  "A Banshee",
  "A Dama Vermelha",
  "A Sereia Negra",
  "A Feiticeira do Pântano",
  "A Rainha de Gelo",
  "O Verme-Rei",
  "O Príncipe da Noite",
  "O Licantropo Alfa",
  "O Rei dos Espectros",
  "O Carniceiro Sem Cara",
  "O Demônio da Meia-Noite",
  "A Viúva Enforcada",
  "O Ceifador Pálido",
  "A Boneca de Porcelana",
  "O Homem de Sebo",
  "A Freira Cega",
  "O Doutor da Peste",
  "O Barqueiro do Aqueronte",
  "A Dama de Preto",
  "O Cavaleiro Sem Cabeça",
  "A Vampira de Praga",
  "O Estripador de Whitechapel",
  "A Alma Penada",
  "O Golem de Barro",
  "A Múmia da Cripta",
  "O Espectro do Farol",
  "A Bruxa de Endor",
  "O Carrasco Encapuzado",
  "A Sirigaita do Cemitério",
  "O Pesadelo de Elm",
  "A Menina do Poço",
  "O Colecionador de Almas",
  "A Dama Branca",
  "O Homem-Bode",
  "A Sombra Rastejante",
  "O Enterrador de Vivos",
  "A Rainha das Aranhas",
  "O Ventríloquo Maldito",
  "A Costureira de Peles",
  "O Regente das Trevas",
  "A Serva de Hécate",
  "O Cão do Inferno",
  "A Dama dos Corvos",
  "O Profeta Cego",
  "A Bailarina Quebrada",
  "O Relojoeiro da Morte",
  "A Súcubo Escarlate",
  "O Barão do Sangue",
  "A Órfã Amaldiçoada",
  "O Homem de Neblina",
  "A Rainha Carmesim",
  "O Espantalho Faminto",
  "A Viúva das Sete Faces",
  "O Grão-Inquisidor",
  "A Sereia dos Naufrágios",
  "O Andarilho da Bruma",
  "A Feiticeira Sem Nome",
  "O Cirurgião Louco",
  "A Dama de Cinzas",
  "O Rei Cadáver",
  "A Sacerdotisa Negra",
  "O Guardião do Ossário",
  "A Bruxa de Salem",
  "O Fantasma da Ópera",
  "A Noiva de Sangue",
  "O Vampiro dos Cárpatos",
  "A Mão Estrangeira",
  "O Duque das Moscas",
  "A Dama Sem Rosto",
  "O Semeador de Pragas",
  "A Rainha dos Mortos",
  "O Homem do Saco",
  "A Feiticeira de Cera",
  "O Cavaleiro da Peste",
  "A Aranha-Rainha do Sótão",
  "O Coveiro Insone",
  "A Dama do Espelho",
  "O Príncipe Escarlate",
  "A Bruxa das Marés",
  "O Palhaço do Esgoto",
  "A Dançarina de Ossos",
  "O Senhor das Sanguessugas",
  "A Viúva de Véu Negro",
  "O Espectro do Manicômio",
  "A Deusa das Lágrimas",
  "O Último Coveiro",
  "A Dama da Foice",
]

// Retorna um vilão ainda não usado; se todos já foram usados, permite repetir.
export function pickVillain(used: string[]): string {
  const disponiveis = VILLAINS.filter((v) => !used.includes(v))
  const pool = disponiveis.length > 0 ? disponiveis : VILLAINS
  return pool[Math.floor(Math.random() * pool.length)]
}
